#!/bin/sh /etc/rc.common
# Copyright (C) 2007-2011 OpenWrt.org

START=80

start_instance() {
	local section="$1"

	config_get sshopt "$section" 'sshopt'
	config_get gatetime "$section" 'gatetime'
	config_get monitorport "$section" 'monitorport'
	config_get poll "$section" 'poll'
	config_get username "$section" 'username'
	config_get password "$section" 'password'
	config_get host "$section" 'host'
	config_get localport "$section" 'localport'
	config_get remoteport "$section" 'remoteport'
	config_get mode "$section" 'mode'

	local ssh="$sshopt -D ${localport:-7070} -p ${remoteport:-22} -l ${username:-root} $host"  

	/etc/init.d/redsocks start $mode
	export SSH_PASSWORD="$password"
	export AUTOSSH_GATETIME="${gatetime:-30}"
	export AUTOSSH_POLL="${poll:-600}"
	export AUTOSSH_MAXSTART="3"
	service_start /usr/sbin/autossh -M ${monitorport:-20000} -f ${ssh}
}

boot() {
	return
}

start() {
	disable=`uci get app.autossh.disable`
        if [ "$disable" -eq 0 ]; then
		config_load 'autossh'
		config_foreach start_instance 'autossh'
	else
                if [ "$disable"  -eq 1 ]; then
                        echo "app has been stopped in uci"
                        return 0
                else
                        echo "status wrong ,please cheek uci config"
                        return 0
                fi
        fi
}

stop() {
	service_stop /usr/sbin/autossh
}
