#!/bin/sh /etc/rc.common

START=99
STOP=10

start() {
	echo "start" > /tmp/state/hwf_health_chk_run_state
}

stop() {
	echo "stop" > /tmp/state/hwf_health_chk_run_state
	killall hwf_health_chk.sh &> /dev/null
}
