#!/bin/sh

. /lib/ralink.sh

bdname=$(tw_board_name)

led_set_attr() {
	[ -f "/sys/class/leds/$1/$2" ] && echo "$3" > "/sys/class/leds/$1/$2"
}

rled_set_timer() {
	led_set_attr $rled "brightness" "255"
	led_set_attr $rled "trigger" "timer"
	led_set_attr $rled "delay_on" "$1"
	led_set_attr $rled "delay_off" "$2"
}


case "$bdname" in
HC5661 | HC5761 | HC5641 | HC5663)
	rled="HC5761:green:system"
	rled_set_timer 100 100
	rled="HC5761:green:internet"
	rled_set_timer 100 100
	;;
HB5981m | HB5981s)
	rled="HC5761:green:system"
	rled_set_timer 100 100
	rled="HC5761:green:wlan-2p4"
	rled_set_timer 100 100
	;;
esac
